# config/routes.rb
Rails.application.routes.draw do
  # Devise routes for user authentication
  devise_for :users

  # Resourceful routes for Tasks
  resources :tasks

  # Resourceful routes for Waste Entries
  resources :waste_entries

  # Root route for the application
  # When a user logs in, Devise will redirect them here by default
  root "home#index"

  # The route generated by `rails generate controller Home index`
  # You can keep this if you want `http://localhost:3000/home/index` to also work,
  # but `root "home#index"` makes `/` go there.
  get "home/index"
end
